### ISSUE TITLE
Internet is disconnected in macOS VM

### ISSUE THREAD

**Issue by Andrey-Raev** [trueToastedCode/ParallelsLab#10]
Hello, I have a serious problem with internet connection disconnection in MacOS Virtual Machine version 14.1 (23B74) and Parallels Desktop version 19.1.0 (54729). 
When I start the MacOS VM, the internet connection works for a while, but after about 5 minutes it shuts down without shutting down again. The only way to start the Internet in a MacOS VM is to completely shut down Parallels Desktop and reboot MacOS VM. Please help me with this problem.

**Comment by trueToastedCode** [comment]
This has nothing to do with the crack. You should rather go into Parallels Forum.
