### ISSUE TITLE
Can you explain the process for noobs, please?

### ISSUE THREAD

**Issue by domoticati** [trueToastedCode/ParallelsLab#12]
I receive the following error: [-] Missing submodule files, perhaps you forgot to execute "git submodule update --init --recursive"

Thanks

**Comment by trueToastedCode** [comment]
I have aleady done that ... Please just follow the usage steps in the README

**Comment by royalts352** [comment]
> I receive the following error: [-] Missing submodule files, perhaps you forgot to execute "git submodule update --init --recursive"
> 
> Thanks

I think you missing this. I had the same issue. Copy the directory like this:

git clone --depth 1 https://github.com/trueToastedCode/ParallelsLab.git
cd ParallelsLab

and then go to the folder
