### ISSUE TITLE
macOS 14.1 M2 Max

### ISSUE THREAD

**Issue by JmeLche** [trueToastedCode/ParallelsLab#13]
![Screenshot 2023-11-09 at 12 09 08](https://github.com/trueToastedCode/ParallelsLab/assets/29265841/d0c74cdc-b63b-48fe-82bb-8816a9fd1293)

**Comment by zapper9595** [comment]
Nope, no issues. 14.1 M2. Run xcode, ensure MACOS is ticked and you see xcode main menu. Then follow https://github.com/trueToastedCode/ParallelsLab#codesign-error
