### ISSUE TITLE
[-] This script is for 19.1.0-54729, but your's is 19.1.1-54734.

### ISSUE THREAD

**Issue by Aopenz** [trueToastedCode/ParallelsLab#15]
the Version upgraded, so scripts not working, should need to upgrade scripts ?
[-] This script is for 19.1.0-54729, but your's is 19.1.1-54734.

**Comment by trueToastedCode** [comment]
Download the older version from the link in the README.

**Comment by Aopenz** [comment]
Aren't you going to challenge the latest version? HAHA!

**Comment by trueToastedCode** [comment]
> Aren't you going to challenge the latest version? HAHA!

It's already cracked, but not with SIP enabled. I don't think we will find a method.
