### ISSUE TITLE
“chmod: install.sh: No such file or directory“ Unable to install properly

### ISSUE THREAD

**Issue by Mithcell-Ma** [trueToastedCode/ParallelsLab#16]
I'm running “5. install” after waiting for Xcode to install IOS (after it's done) and this is what I'm getting.

I tried to start from step 4 and install again.  
fatal: destination path 'ParallelsLab' already exists and is not an empty directory.

**Comment by trueToastedCode** [comment]
So either go into the ParallelsLab (`cd ParallelsLab`) and run the installer again or delete the directory with `sudo rm -rf ParallelsLab` in order to be able to reclone. But you could also reset the folder using `git reset --hard HEAD`.

Ps: Guys please just ask ChatGPT, it's way faster

**Comment by Mithcell-Ma** [comment]
Thank you so much
