### ISSUE TITLE
Is there any problem when updating to 19.1.1?

### ISSUE THREAD

**Issue by domoticati** [trueToastedCode/ParallelsLab#19]
Thnks for everything!! It works perfectly, but now every time I started it tells me I have to update. Is there any problem when updating, or it still working?

**Comment by trueToastedCode** [comment]
> Thnks for everything!! It works perfectly, but now every time I started it tells me I have to update. Is there any problem when updating, or it still working?

No, you can't update using this source at the moment. 19.1.1 will be published soon but it will have limitations (choice between security or no USB).
