### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by jonniiebo** [trueToastedCode/ParallelsLab#23]
hey I just tried the step-by-step directions and when I Start up parallels it opens the standard login screen
no idea how to go form that
any ideas how to fix that issue?

**Comment by trueToastedCode** [comment]
Some errors must have occurred, cause when on successful installation the login screen should not appear.

**Comment by jonniiebo** [comment]
user error, terminal didn't have full diskaccess, now its running perfect
