### ISSUE TITLE
Sorry this is not an issue but I'm not sure about how to install it.

### ISSUE THREAD

**Issue by AmareIly** [trueToastedCode/ParallelsLab#27]
Sorry this is not an issue but I'm not sure about how to install it. 

After this step:
Clone the respository
git clone --depth 1 https://github.com/trueToastedCode/ParallelsLab.git && cd ParallelsLab && git submodule update --init --recursive

- I have the repository on Documents, and I don't know what to do in the next step.

Install
chmod +x install.sh && chmod +x reset.command && sudo ./install.sh <mode>

(<"mode"> caracters does't appears here but I pasted them)

- I copied and pasted that code on terminal and i got: zsh: parse error near `\n'

Please could I get some help?

<img width="586" alt="Captura de pantalla 2023-11-23 a la(s) 03 12 51" src="https://github.com/trueToastedCode/ParallelsLab/assets/151821591/74dce5e5-240f-4f49-a27c-f2ff4459ecc1">

**Comment by trueToastedCode** [comment]
<mode> is a placeholder you should have exchanged for one of the available modes.

**Comment by Volterzero89** [comment]
Hello, thank you for work. 
I'm having the same issues as [AmareIly].

I copied and pasted that code on terminal and i got: zsh: parse error near `\n'

I tried replacing "<mode>" with "<downgrade_vm>" as you suggested in your reply but nothing changed. I've also read resolved issues but i just can't get it.

Just to give you background I've installed paralle, it set wiundows up but i did not log in any account and closed the app. 

Thank you in advance for your support

**Comment by trueToastedCode** [comment]
Guys, you have to remove the angle brackets. This is just a common convention used to denote placeholders.

**Comment by Volterzero89** [comment]
I'm reeling feelin dumb at the moment. 
Still, it doesn't work 😓

<img width="743" alt="Screenshot 2023-11-23 alle 17 00 04" src="https://github.com/trueToastedCode/ParallelsLab/assets/151854373/f8651f5b-768d-4fee-8356-d227c4025dab">

**Comment by trueToastedCode** [comment]
> I'm reeling feelin dumb at the moment. Still, it doesn't work 😓
> <img alt="Screenshot 2023-11-23 alle 17 00 04" width="743" src="https://user-images.githubusercontent.com/151854373/285260285-f8651f5b-768d-4fee-8356-d227c4025dab.png">

You are not within the ParallelsLab directory.

**Comment by Volterzero89** [comment]
Could you please explain us how to get there? 

I've tried sticking to the read.me but as you can see I, and I believe also the other commentators, are not used to coding. Apologies in advance for wasting any of your time, your support is much apreciated.

**Comment by trueToastedCode** [comment]
> Could you please explain us how to get there?
> 
> I've tried sticking to the read.me but as you can see I, and I believe also the other commentators, are not used to coding. Apologies in advance for wasting any of your time, your support is much apreciated.

Using Finder, you can click on the ParallelsLab directory and then press Command+Option+c, which will copy the path. In the Terminal you can then go there using `cd "<path>"` (angle brackets and path needs to be replaced by pasting the actual path there).

**Comment by Volterzero89** [comment]
Ok, I managed to open the folder in the terminal, it's a step forward! Still no clue of what to do 😂

<img width="915" alt="Screenshot 2023-11-23 alle 17 19 35" src="https://github.com/trueToastedCode/ParallelsLab/assets/151854373/549b7b64-cb60-4618-b057-f8b4761bea86">

To all of my noob friends, to open the correct folder in the terminal just follow the last entry here https://support.apple.com/it-it/guide/terminal/trmlb20c7888/mac#:~:text=On%20your%20Mac%2C%20open%20a,window%3A%20Choose%20Open%20in%20Terminal.

**Comment by Volterzero89** [comment]
it looks like everything has worked now! I got it processing and I saw all the green lines! Yay!

Am supposed to regularly login now?
![image](https://github.com/trueToastedCode/ParallelsLab/assets/151854373/38c0c929-a420-45cf-a6f8-c8425e2771d2)

**Comment by trueToastedCode** [comment]
> it looks like everything has worked now! I got it processing and I saw all the green lines! Yay!
> 
> Am supposed to regularly login now? ![image](https://user-images.githubusercontent.com/151854373/285266921-38c0c929-a420-45cf-a6f8-c8425e2771d2.png)

Mh... in the account & license area, a fake license should have appeared... i think some error occurred. See the script will for some errors not stop the execution. In #23 an issue like that as been resolved.

**Comment by Volterzero89** [comment]
Confirming the problem has been solved with issue #23!
Many thanks for your great support.
