### ISSUE TITLE
[-] Compiled insert_dylib binary not found.

### ISSUE THREAD

**Issue by Mintume** [trueToastedCode/ParallelsLab#29]
I did as you described and used no_sip mode as I disabled my sip.
But I am getting error with last command: I have command line and Xcode app both installed.

"chmod +x install.sh && chmod +x reset.command && sudo ./install.sh no_sip
[*] Compiling...
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[-] Compiled insert_dylib binary not found."

**Comment by trueToastedCode** [comment]
Probable the same issue as #5

**Comment by Mintume** [comment]
Thanks.. it worked now.
