### ISSUE TITLE
fatal: not a git repository

### ISSUE THREAD

**Issue by Qvinto1** [trueToastedCode/ParallelsLab#3]
HI,

When executing "git submodule update --init --recursive && chmod +x install.sh && chmod +x reset.command && sudo ./install.sh" terminal gives the following error "fatal: not a git repository (or any of the parent directories): .git"
Any advice? thanks

**Comment by trueToastedCode** [comment]
This makes me wonder, if you've even cloned the respository before running these commands...
```
git clone --depth 1 https://github.com/trueToastedCode/ParallelsLab.git
cd ParallelsLab
```

**Comment by Qvinto1** [comment]
Thanks that has fixed it. Perhaps it might be good to add this to the instructions for less git savvy users. Thanks for all your work on this

**Comment by moshawin** [comment]
> HI,
> 
> When executing "git submodule update --init --recursive && chmod +x install.sh && chmod +x reset.command && sudo ./install.sh" terminal gives the following error "fatal: not a git repository (or any of the parent directories): .git" Any advice? thanks

after this command i see

[*] Compiling...
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[-] Compiled insert_dylib binary not found.
serhii@MacBook-Pro-Serhii ParallelsLab % 

What am i need to do?

**Comment by royalts352** [comment]
have the same 

> > HI,
> > When executing "git submodule update --init --recursive && chmod +x install.sh && chmod +x reset.command && sudo ./install.sh" terminal gives the following error "fatal: not a git repository (or any of the parent directories): .git" Any advice? thanks
> 
> after this command i see
> 
> [*] Compiling... xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance [-] Compiled insert_dylib binary not found. serhii@MacBook-Pro-Serhii ParallelsLab %
> 
> What am i need to do?

have the same issue but let you guys know I am a noob :D
