### ISSUE TITLE
Wrong script version

### ISSUE THREAD

**Issue by Pauldu90** [trueToastedCode/ParallelsLab#34]
Hi, I guess my problem could be resolved very easily, but I don't really know how... I'm trying to install [the other commit instead](https://github.com/trueToastedCode/ParallelsLab/tree/5525d1faf934a27d0adf8a7e96a4ef2e9a240001), such as it's described to get the Mac VM implemented.
At the step 5, I have this message :
`Paul@MacBook-Pro-de-Paul ParallelsLab % chmod +x install.sh && chmod +x reset.command && sudo ./install.sh downgrade_vm`
`[-] This script is for 19.1.1-54734, but your's is 19.1.0-54729. `

 How could I install the script for 19.1.0-54729 ?

**Comment by trueToastedCode** [comment]
Duplication of #30
