### ISSUE TITLE
Notify wrong processor on Mac M1 Pro

### ISSUE THREAD

**Issue by freudmaster** [trueToastedCode/ParallelsLab#37]
Hello, first of all, I thank you all for your works here.
I face an issue when I try to apply the downgrade vm mode, after applying it successfully I am unable to launch vm I get a message that inform me that I'm on Intel processor and I try to launch a arm64 vm but my Mac is a Macbook pro M1 Pro who is effectively on arm64.
NB : before launching the patch, with the trivial version of the soft the vm work properly but as soon as I install the patch nothing work.
Can you help me with that ?

**Comment by trueToastedCode** [comment]
Please open a Terminal and execute `arch`... Maybe you have activated Rosetta.

**Comment by freudmaster** [comment]
thank you for your reply exactly, I have activated rosetta, so the install command should be `arch sudo ./install.sh downgrade_vm` ?

**Comment by freudmaster** [comment]
finally, I just deactivate rosetta for the execution, thank you for your help I can close the topic
