### ISSUE TITLE
macked doesn't work. Only the OLD method works!

### ISSUE THREAD

**Issue by ballo** [trueToastedCode/ParallelsLab#38]
I used the newer closed source "macked" method to no avail: it would ask me to sign in (not a problem I ever encountered with other bypass methods). 

I read the README although it's very sparse on details and is based on the old(?) non-macked package. I'm a coder and this is beyond confusing, perhaps because the author isn't a native English speaker. 

Since the macked binary gave the above problem I also ran the older method which the README actually refers to (why make it this convoluted?) I reinstalled Parallels and tried the old method with downgrade_vm and it worked. 

For those who want to do this, you have to do a weird hybrid of following and not following the README because the author has made it very confusing. INSTEAD of following the README, you have to do the following:

git clone https://github.com/alsyundawy/Parallels
cd Parallels
git submodule update --init --recursive

then you can run step 6 in the README (which curiously would never work if you followed step 5)

**Comment by ClementBarreda** [comment]
I have a similar problem. After following all the steps, when I launch Paralels it asks me to sign in. Can't get it to work, I don't understand why...

**Comment by trueToastedCode** [comment]
> > I have a similar problem. After following all the steps, when I launch Parallels it asks me to sign in. Can't get it to work, I don't understand why...
> 
> Don't use the app. Instead follow the instructions I outlined above (the readme on that repo is STILL WRONG!)

Consider making a pull request.
