### ISSUE TITLE
Parallels Tools not activated

### ISSUE THREAD

**Issue by ptoolscrackbegger** [trueToastedCode/ParallelsLab#4]
I would like to know if it was possible to activate parallels toolbox using this method because I don't think it was activated.
Thanks for the awesome project, had no issues with the main parallels program 👌

**Comment by trueToastedCode** [comment]
Thank you for your feedback. Unfortunately, currently this project only targets Parallels Desktop. I do not have plans for Parallels Tools.

**Comment by ptoolscrackbegger** [comment]
No problem, have a nice day
