### ISSUE TITLE
Always prompted to update Parallels Tools

### ISSUE THREAD

**Issue by ClementBarreda** [trueToastedCode/ParallelsLab#40]
Each time I start the VM and log in into it, I have a pop-up that's said "Update Parallels Tools". 

Image : 
<img width="444" alt="Capture d’écran 2023-12-05 à 23 11 53" src="https://github.com/trueToastedCode/ParallelsLab/assets/133324408/d1ebbfd2-859b-43a3-a46b-1d57f10d149b">

**Comment by trueToastedCode** [comment]
#33
