### ISSUE TITLE
Activation Tool Deletes Parallels

### ISSUE THREAD

**Issue by gil-sanders** [trueToastedCode/ParallelsLab#42]
I am running a Macbook Pro 16 Inch Intel i9 processor. It's a fresh new install of Mac OS Sonoma, and I downloaded Xcode and its Mac OS components. I made sure I downloaded version 54734 of Parallels 19.1.1, but every time I run the Activation Tool, it deletes the program from my Mac. 

Is anyone else having this issue?

**Comment by trueToastedCode** [comment]
Which branch are you referring to?

**Comment by gil-sanders** [comment]
I'm referring to this branch: https://github.com/trueToastedCode/ParallelsLab.git. I downloaded the .zip file. I used Activation Tool 4.3.1, and then downgrade to 4.2 because that worked just fine on my i7 Macbook Pro. But no matter what version of Parallels I use (as low as 19.0.0), the patcher just deletes the application.
 
I do have SIP enabled, and I am using my Mac under a non-admin user for security purposes. I just su - admin in Terminal to run admin level commands from my standard user, and I gave Terminal full disk access as well as App Management access. I have tried to sudo into that tool-looking icon inside the ActivateTool-4.3.1.dmg file and it'll say "Repair successful! You can now run the Parallels Desktop Activation Tool normally." But I don't think the Activation Tool is quarantined to begin with because running that xattr command gives me this result: "No such xattr: com.apple.quarantine." 

Whenever I run the Activation Tool I get this Chinese error, which says "Failed to install patch: Try it after reinstalling Parallels Desktop." Then it just deletes my Parallels Desktop application. I reinstalled Parallels and same problem. I removed all files with App Cleaner, and manually removed the cloned git in the root of the admin user folder. So I thought, "Maybe I have to activate the trial and then install a VM." I activated the trial and installed Windows 10. But the Activation Tool still deleted the program. I used Little Snitch to block all connections from Parallels. 

I logged out / restarted my Macbook Pro. Not sure what I am doing wrong here. Is Parallels monitoring the Applications folder for any changes and deleting it before the Activation Tool can do anything?

**Comment by gil-sanders** [comment]
In the console, I see this happening: 

> 12-09 17:47:18.095 F /prllog:7249:10a46/ pdfm-bootstrap: watchdog[7244]: Stop watching /Applications/Parallels Desktop.app/Contents/MacOS/prl_naptd
> 12-09 17:47:18.109 F /prllog:7257:10a55/ pdfm-bootstrap: watchdog[7244]: file /var/run/prl_watchdog-ebdba5702a20.pid, pid 
> 12-09 17:47:18.114 F /prllog:7258:10a5d/ pdfm-bootstrap: watchdog[7244]: No self watchdog found
> 12-09 17:47:18.120 F /prllog:7259:10a5f/ pdfm-bootstrap: watchdog[7244]: /Applications/Parallels Desktop.app/Contents/MacOS/prl_naptd stop
> 12-09 17:47:18.160 F /service-wrap:7261:10a67/ Is executed with params 'service_stop /Applications/Parallels Desktop.app'
> 12-09 17:47:18.169 F /service-wrap:7261:10a67/ Stopping Parallels Dispatcher Service
> 12-09 17:47:18.170 F /service-wrap:7261:10a67/ Parallels Dispatcher Service is not running
> 12-09 17:47:18.184 F /prldirs:7268:10a73/ ParallelsDirs::Init( ) was called. Current app mode = 1 ( DESKTOP ) build version: 19.1.1 (54734) Sat, 04 Nov 2023 05:20:37
> 12-09 17:47:18.202 F /prldirs:7269:10a76/ ParallelsDirs::Init( ) was called. Current app mode = 1 ( DESKTOP ) build version: 19.1.1 (54734) Sat, 04 Nov 2023 05:20:37
> 12-09 17:47:18.205 F /service-wrap:7261:10a67/ Stopping Parallels networking
> 12-09 17:47:18.205 F /service-wrap:7261:10a67/ error Cannot find pid for /Applications/Parallels Desktop.app/Contents/MacOS/prl_naptd
> 12-09 17:47:18.208 F /service-wrap:7261:10a67/ Parallels Services have stopped

I followed every step of the instructons, including editing the hosts file just incase Little Snitch was not working properly. I logged out and then cloned the repostiory.

**Comment by gil-sanders** [comment]
Nvm, I solved the problem. I needed to run the Activation Tool through the admin account. Everything worked just fine once I did that.
