### ISSUE TITLE
Error "Compiled insert_dylib binary not found."

### ISSUE THREAD

**Issue by sarpysarpy** [trueToastedCode/ParallelsLab#5]
I get the following error during installation
```

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[-] Compiled insert_dylib binary not found.
```

**Comment by trueToastedCode** [comment]
This is likely the result of not following the usage instructions:
> 3. Install [Xcode from the App Store](https://apps.apple.com/us/app/xcode/id497799835?mt=12)
Open it afterwards and install the default components (iOS and MacOS, which cannot be unchecked)

And perhaps you should also `xcode-select --install`.

**Comment by sarpysarpy** [comment]
I found the issue which was described here: https://stackoverflow.com/a/17980786

Works now after performing the command:
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by royalts352** [comment]
GUys how to block the P Servers on a Mac?
