### ISSUE TITLE
Whats the point of the xcode that we got to download?

### ISSUE THREAD

**Issue by fishfoodisgood** [trueToastedCode/ParallelsLab#7]

**Comment by fishfoodisgood** [comment]
Like is there any thing you got to do?

**Comment by trueToastedCode** [comment]
> Whats the point of the xcode that we got to download?

Xcode is necessary, to compile the project. Traditionally, cracks are famous an origin of malware. So by compiling from source, this eliminates any doubt a user might have.
> Like is there any thing you got to do?

I don't understand, what's that referring to. You will obviously need to follow the usage steps.
