### ISSUE TITLE
Fatal error: not a git repository (or any parent directory)

### ISSUE THREAD

**Issue by caocao00027** [trueToastedCode/ParallelsLab#9]
I'm not a software engineer, I don't know what these codes mean, I followed your steps and ended up with Fatal error: not a git repository (or any parent directory), please tell me how to solve this, thanks!

**Comment by trueToastedCode** [comment]
> I'm not a software engineer, I don't know what these codes mean, I followed your steps and ended up with Fatal error: not a git repository (or any parent directory), please tell me how to solve this, thanks!

#3
